version: '3'

services:
  db:
    # Dockerfile이 있는 위치
#    build: ./src/database
    image: mysql:5.7
    container_name: mysql-con
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - TZ=Asia/Seoul
    volumes:
      - ./src/database/scripts:/docker-entrypoint-initdb.d
    # 내부에서 개방할 포트 : 외부에서 접근할 포트
    ports:
      - '3306:3306'
  redis:
    image: redis:6
    container_name: redis-con
    command: redis-server --port 6379
    ports:
      - '6379:6379'
  app:
    build: .
    image: app-img
    container_name: app-con
    # 연결할 외부 디렉토리 : 컨테이너 내 디렉토리
    volumes:
      - ./:/home/web-app
    # 환경변수 설정
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    ports:
      - '3000:3000'
    depends_on:
      - db